server:
  port: 8008
spring:
  datasource:
    #serverTimezone=UTC  没有这个将报错mysql errorCode 0, state 01S00
    url: jdbc:mysql://localhost:3306/psy_dailog_sys?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 19960601
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
      name: psy_server
  jpa:
    database: MySQL
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update
      #如果bean中使用@column指定对应的数据库字段名称 应使用如下配置 。 否则应将驼峰名称改为jpa默认的_分隔
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

eureka:
  client:
    #是否把自己注册进eureka  服务端false  客户端true
    register-with-eureka: true
    #是否从eurekaserver抓取已有的注册信息 默认为true 单节点无所谓 集群必须设置了才能配合ribbon做负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka
